### ISSUE TITLE
Github pull requiring access token

### ISSUE THREAD

**Issue by phurth** [MichelFR/MqDockerUp#216]
This app is working great for 17 out of 18 containers. The one that fails happens to be in the Github registry (ghcr.io). The others are all Docker Hub and update as expected.

For this one container, the following error is logged:
```
2024/01/25 14:39:29 | stdout | [90m25.01.2024 20:39:29[0m [[33mwarn[39m]  Failed to find new digest for image ghcr.io/wez/govee2mqtt:latest
-- | -- | --
2024/01/25 14:39:29 | stdout | [90m25.01.2024 20:39:29[0m [[31merror[39m]  Github access token is not defined
```

I understand there is an option to include an access token in the config, but this raises two questions:

1. Why is a token required for a simple pull - is this a ghcr.io limitation?
2. If this is required, how does one get a auth token? The only info I can find is regarding auth tokens to access one's own app, not the public repository.

Thanks in advance!
Pete

**Comment by MichelFR** [comment]
This is a limitation of ghcr.io

I cannot check the newest digest (hash of latest image) without going of the official api which require the access token
