### ISSUE TITLE
ERROR SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by SirBen88** [MichelFR/MqDockerUp#238]
When installing MqDockerUp fresh, an error occurs during the initial step:
SQLITE_CANTOPEN: unable to open database file.

This issue arises because the 'data' folder is missing and is not created automatically. Manually creating the folder resolves the error message.

**Comment by Geulopa** [comment]
bonjour j'ai le même message d'erreur avez vous une idée?
merci

**Comment by Geulopa** [comment]
Bonjour j'ai cette erreur

![2024-05-08_09h30_42](https://github.com/MichelFR/MqDockerUp/assets/97992821/a9716ea8-02ba-4124-a422-afd656a8347a)

**Comment by SirBen88** [comment]
Do you have a `database.db` file located in the folder `MqDockerUp/data`?
If yes, what are the permissions of the `data` folder?

**Comment by Geulopa** [comment]
> Avez-vous un `database.db`fichier situé dans le dossier `MqDockerUp/data`? Si oui, quelles sont les autorisations du `data`dossier ?

Bonjour non le dossier est vide au niveau des autorisations je n'ai rien touché y a t'il une commande a faire pour donner les droits
merci

**Comment by SirBen88** [comment]
Have you modified your docker command: `-v your/path/data:/app/data/ \`
or your docker compose parameter:  `- your/path/data:/app/data/ # This is required to store the data (database.db)`
This path must match to your data folder.

**Comment by Geulopa** [comment]
j'ai fait comme ça

![image](https://github.com/MichelFR/MqDockerUp/assets/97992821/0c41c546-4984-446e-b3eb-c8e8d3f31f9d)

**Comment by SirBen88** [comment]
Try this: 
`- /home/mqdockerup/data:/app/data/ # This is required to store the data (database.db)`

**Comment by Geulopa** [comment]
merci ça fonctionne

**Comment by SirBen88** [comment]
You are welcome. I think this issue can be closed. data folder will be created.
