### ISSUE TITLE
Too many requests: Rate limit exceeded

### ISSUE THREAD

**Issue by Grandma-Betty** [MichelFR/MqDockerUp#290]
I've just installed MqDockerUp for the first time. I have three hosts providing different docker containers, so I installed MqDockerUp on all three hosts.
Now I have one general question and one issue:

**Question:** Is it possible to just install a single instance of MqDockerUp whoch would manage/monitor also docker images on different hosts?

**Issue:** All docker images from every of my three hosts are showing up in Home Assistant. The available docker image updates were showing up for a minute or so but then they disappeared and now I got this message when I want to check the official docker hub website:

![Screenshot 2024-05-08 172156](https://github.com/MichelFR/MqDockerUp/assets/48346793/e44f5ef6-6551-444b-a6c5-35a845de9fd7)

Any idea why this could be happening?

Sidenote: I don't know if this does matter in any way, but two of my hosts are in a different subnet so I only allowed port 1883 from the two hosts to my Home Assistant instance through the firewall. I guess this is enough to make everything work as intended and should not generate this issue, right?

Thank you in advance!

**Comment by arrikhan** [comment]
Whilst the interval configuration might resolve this (I too have this problem and have disabled mqdockerup as a result), it could do with a separate configuration for polling version checks.

Up time is critical, so you want to poll regularly. 

Version change is not, so having a more relaxed option here would be very useful (drop it in a cache? and poll less often?)

I'd really like to keep using this but might have to find other means to monitor container uptime (ie: prometheus) and feed back into HA.

**Comment by mcsdodo** [comment]
+1 for separate configuration for polling new images. Or even an option to turn it off - just trigger update manually. High frequency for polling running containers' state is desirable. New versions - that doesn't need to run so often.
