### ISSUE TITLE
TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by Caros2017** [MichelFR/MqDockerUp#37]
Hey! Thanks for the fix! I updated mqdockerup and now I see all containers in Home Assistant, but some of them are just filled with unknown values, some are fine. also in container log I get this error, the container restarts every time:

```
> mqdockerup@0.14.5 start
> node dist/src/index.js
  __  __       ____             _             _   _       
 |  \/  | __ _|  _ \  ___   ___| | _____ _ __| | | |_ __  
 | |\/| |/ _` | | | |/ _ \ / __| |/ / _ \ '__| | | | '_ \ 
 | |  | | (_| | |_| | (_) | (__|   <  __/ |  | |_| | |_) |
 |_|  |_|\__, |____/ \___/ \___|_|\_\___|_|   \___/| .__/ 
            |_|                                    |_|    
Starting MqDockerUp V0.14.5 ... 
24.03.2023 14:57:09 [info] 	Connected to MQTT broker
24.03.2023 14:57:09 [info] 	Checking for new/old containers...
24.03.2023 14:57:10 [info] 	Checking for image updates...
24.03.2023 14:57:10 [info] 	Image micrib/mqdockerup:latest is up-to-date
24.03.2023 14:57:10 [info] 	New version available for image nbr23/youtube-dl-server:yt-dlp
24.03.2023 14:57:11 [warn] 	Failed to find new digest for image vonproteus/podcast-generator:latest
24.03.2023 14:57:11 [error] 	MqDockerUp stopped due to an error
24.03.2023 14:57:11 [error] 	object
24.03.2023 14:57:11 [error] 	TypeError: Cannot read properties of null (reading 'data')
    at Function.<anonymous> (/app/src/services/HomeassistantService.ts:236:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/dist/src/services/HomeassistantService.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

_Originally posted by @PeteSSMMSS in https://github.com/MichelFR/MqDockerUp/issues/21#issuecomment-1482945505_

**Comment by Caros2017** [comment]
Created this issue, I am experiencing the exact same behaviour after the update

**Comment by frittes** [comment]
Same issue here.

**Comment by MichelFR** [comment]
Thanks for opening a new issue. 

Im looking into it, might be just a simple oversight.

**Comment by MichelFR** [comment]
This may be fixed now so that MqDockerUp is not stopped when it occurs, it should additonally output more information to the logs.
If you see any related errors please feel free to contact me

**Comment by Caros2017** [comment]
> This may be fixed now so that MqDockerUp is not stopped when it occurs, it should additonally output more information to the logs. If you see any related errors please feel free to contact me

Cool thanks! Can you update the docker container on DockerHub to v0.14.6 so I can test it?

**Comment by MichelFR** [comment]
Created a release right now, images should be up in 2-3 minutes

**Comment by frittes** [comment]
Same error with 0.14.6.

```
  __  __       ____             _             _   _       
 |  \/  | __ _|  _ \  ___   ___| | _____ _ __| | | |_ __  
 | |\/| |/ _` | | | |/ _ \ / __| |/ / _ \ '__| | | | '_ \ 
 | |  | | (_| | |_| | (_) | (__|   <  __/ |  | |_| | |_) |
 |_|  |_|\__, |____/ \___/ \___|_|\_\___|_|   \___/| .__/ 
            |_|                                    |_|    
Starting MqDockerUp V0.14.6 ... 

29.03.2023 16:40:27 [info] 	Connected to MQTT broker
29.03.2023 16:40:27 [info] 	Checking for new/old containers...
29.03.2023 16:40:27 [info] 	Checking for image updates...
29.03.2023 16:40:28 [info] 	Image micrib/mqdockerup:latest is up-to-date
29.03.2023 16:40:29 [info] 	Image esphome/esphome:latest is up-to-date
29.03.2023 16:40:30 [error] 	MqDockerUp stopped due to an error
29.03.2023 16:40:30 [error] 	object
29.03.2023 16:40:30 [error] 	TypeError: Cannot read properties of null (reading 'data')
    at Function.<anonymous> (/app/src/services/HomeassistantService.ts:237:19)
    at Generator.next (<anonymous>)
    at fulfilled (/app/dist/src/services/HomeassistantService.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by PeteSSMMSS** [comment]
same :(

**Comment by PeteSSMMSS** [comment]
hey! 0.14.8 seems to work for me, can see some of my containers in HA - some are still missing, this are the container logs:

> 29.03.2023 18:29:15 [warn] 	Failed to find new digest for image vonproteus/podcast-generator:latest
29.03.2023 18:29:15 [error] 	No Images found:
29.03.2023 18:29:15 [error] 	null
29.03.2023 18:29:15 [warn] 	Failed to find new digest for image php:7-fpm-alpine
29.03.2023 18:29:15 [warn] 	Failed to find new digest for image radhifadlillah/shiori:latest
29.03.2023 18:29:16 [info] 	New version available for image joplin/server:latest
29.03.2023 18:29:16 [error] 	No Images found:
29.03.2023 18:29:16 [error] 	null
29.03.2023 18:29:16 [warn] 	Failed to find new digest for image postgres:latest
29.03.2023 18:29:16 [error] 	No Images found:
29.03.2023 18:29:16 [error] 	null
29.03.2023 18:29:16 [warn] 	Failed to find new digest for image docker.io/library/postgres:13
29.03.2023 18:29:16 [error] 	No Images found:
29.03.2023 18:29:16 [error] 	null
29.03.2023 18:29:16 [warn] 	Failed to find new digest for image ghcr.io/paperless-ngx/paperless-ngx:latest
29.03.2023 18:29:17 [error] 	No Images found:
29.03.2023 18:29:17 [error] 	null
29.03.2023 18:29:17 [warn] 	Failed to find new digest for image docker.io/library/redis:6.0
29.03.2023 18:29:17 [info] 	New version available for image benkl/firefly-iii-fints-importer:latest
29.03.2023 18:29:17 [error] 	No Images found:
29.03.2023 18:29:17 [error] 	null
29.03.2023 18:29:17 [warn] 	Failed to find new digest for image alpine:latest
29.03.2023 18:29:17 [info] 	New version available for image fireflyiii/core:latest
29.03.2023 18:29:18 [error] 	No Images found:
29.03.2023 18:29:18 [error] 	null
29.03.2023 18:29:18 [warn] 	Failed to find new digest for image redis:latest
29.03.2023 18:29:18 [info] 	Image gotify/server:latest is up-to-date
29.03.2023 18:29:18 [info] 	Image portainer/portainer-ce:latest is up-to-date
29.03.2023 18:29:19 [info] 	New version available for image fmartinou/whats-up-docker:latest
29.03.2023 18:29:19 [info] 	New version available for image wger/apache:latest
29.03.2023 18:29:19 [info] 	Image sissbruecker/linkding:latest is up-to-date
29.03.2023 18:29:19 [error] 	No Images found:
29.03.2023 18:29:19 [error] 	null
29.03.2023 18:29:19 [warn] 	Failed to find new digest for image docker.io/library/postgres:13
29.03.2023 18:29:20 [info] 	New version available for image louislam/uptime-kuma:latest
29.03.2023 18:29:20 [error] 	No Images found:
29.03.2023 18:29:20 [error] 	null
29.03.2023 18:29:20 [warn] 	Failed to find new digest for image postgres:latest
29.03.2023 18:29:20 [warn] 	Failed to find new digest for image philhawthorne/ha-dockermon:latest
29.03.2023 18:29:23 [info] 	New version available for image grafana/loki:latest
29.03.2023 18:29:23 [info] 	Finished checking for image updates
29.03.2023 18:29:23 [info] 	Next check in 5 minutes


and in home assistant log these here:

> 2023-03-29 17:05:52.248 WARNING (MainThread) [homeassistant.components.mqtt.discovery] Received message on illegal discovery topic 'homeassistant/sensor/ghcr.io_paperless-ngx_paperless-ngx_latest/docker_id/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
2023-03-29 17:05:52.248 WARNING (MainThread) [homeassistant.components.mqtt.discovery] Received message on illegal discovery topic 'homeassistant/sensor/ghcr.io_paperless-ngx_paperless-ngx_latest/docker_name/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
2023-03-29 17:05:52.249 WARNING (MainThread) [homeassistant.components.mqtt.discovery] Received message on illegal discovery topic 'homeassistant/sensor/ghcr.io_paperless-ngx_paperless-ngx_latest/docker_status/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
2023-03-29 17:05:52.250 WARNING (MainThread) [homeassistant.components.mqtt.discovery] Received message on illegal discovery topic 'homeassistant/sensor/ghcr.io_paperless-ngx_paperless-ngx_latest/docker_uptime/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
2023-03-29 17:05:52.255 WARNING (MainThread) [homeassistant.components.mqtt.discovery] Received message on illegal discovery topic 'homeassistant/sensor/ghcr.io_paperless-ngx_paperless-ngx_latest/docker_ports/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
2023-03-29 17:05:52.258 WARNING (MainThread) [homeassistant.components.mqtt.discovery] Received message on illegal discovery topic 'homeassistant/sensor/ghcr.io_paperless-ngx_paperless-ngx_latest/docker_image/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
2023-03-29 17:05:52.259 WARNING (MainThread) [homeassistant.components.mqtt.discovery] Received message on illegal discovery topic 'homeassistant/sensor/ghcr.io_paperless-ngx_paperless-ngx_latest/docker_tag/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic
2023-03-29 17:05:52.261 WARNING (MainThread) [homeassistant.components.mqtt.discovery] Received message on illegal discovery topic 'homeassistant/sensor/ghcr.io_paperless-ngx_paperless-ngx_latest/docker_registry/config'. The topic contains not allowed characters. For more information see https://www.home-assistant.io/docs/mqtt/discovery/#discovery-topic

**Comment by frittes** [comment]
With the new release I have 4 of 16 containers working. The others are removed after finished task.

```
29.03.2023 18:31:05 [info] 	Image esphome/esphome:latest is up-to-date
29.03.2023 18:31:05 [error] 	No Images found:
29.03.2023 18:31:05 [error] 	null
29.03.2023 18:31:05 [warn] 	Failed to find new digest for image ghcr.io/home-assistant/home-assistant:stable
```

esphome is also not available, but the state seems ok in the log.

**Comment by frittes** [comment]
For me it is still not working:



```
  __  __       ____             _             _   _       
 |  \/  | __ _|  _ \  ___   ___| | _____ _ __| | | |_ __  
 | |\/| |/ _` | | | |/ _ \ / __| |/ / _ \ '__| | | | '_ \ 
 | |  | | (_| | |_| | (_) | (__|   <  __/ |  | |_| | |_) |
 |_|  |_|\__, |____/ \___/ \___|_|\_\___|_|   \___/| .__/ 
            |_|                                    |_|    
Starting MqDockerUp V0.16.1 ... 

24.04.2023 19:51:02 [info] 	Connected to MQTT broker
24.04.2023 19:51:02 [info] 	Checking for new/old containers...
24.04.2023 19:51:02 [info] 	Checking for image updates...
24.04.2023 19:51:02 [info] 	Image micrib/mqdockerup:latest is up-to-date
24.04.2023 19:51:03 [error] 	No Images found:
24.04.2023 19:51:03 [error] 	null
24.04.2023 19:51:03 [warn] 	Failed to find new digest for image ghcr.io/home-assistant/home-assistant:stable
24.04.2023 19:51:03 [error] 	No Images found:
24.04.2023 19:51:03 [error] 	null
24.04.2023 19:51:03 [warn] 	Failed to find new digest for image ghcr.io/esphome/esphome:latest
24.04.2023 19:51:03 [warn] 	Failed to find new digest for image nodered:latest
24.04.2023 19:51:03 [info] 	New version available for image zwavejs/zwave-js-ui:latest
24.04.2023 19:51:04 [info] 	Image koenkk/zigbee2mqtt:latest is up-to-date
24.04.2023 19:51:04 [info] 	New version available for image dpage/pgadmin4:latest
24.04.2023 19:51:04 [error] 	No Images found:
24.04.2023 19:51:04 [error] 	null
24.04.2023 19:51:04 [warn] 	Failed to find new digest for image lscr.io/linuxserver/code-server:latest
24.04.2023 19:51:04 [info] 	New version available for image acockburn/appdaemon:latest
24.04.2023 19:51:05 [info] 	Image hkotel/mealie:api-v1.0.0beta-5 is up-to-date
24.04.2023 19:51:05 [info] 	Image hkotel/mealie:frontend-v1.0.0beta-5 is up-to-date
24.04.2023 19:51:05 [error] 	No Images found:
24.04.2023 19:51:05 [error] 	null
24.04.2023 19:51:05 [warn] 	Failed to find new digest for image lscr.io/linuxserver/cloud9:latest
24.04.2023 19:51:05 [info] 	New version available for image portainer/portainer-ce:latest
24.04.2023 19:51:06 [warn] 	Failed to find new digest for image rhasspy/rhasspy:latest
24.04.2023 19:51:06 [warn] 	Failed to find new digest for image postgres:14.1-alpine
24.04.2023 19:51:06 [info] 	New version available for image eclipse-mosquitto:latest
24.04.2023 19:51:06 [info] 	Finished checking for image updates
24.04.2023 19:51:06 [info] 	Next check in 5 minutes
24.04.2023 19:51:06 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
24.04.2023 19:51:06 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
24.04.2023 19:51:06 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
```

**Comment by MichelFR** [comment]
> For me it is still not working:
> 
> 
> 
> 
> 
> 
> 
> ```
> 
>   __  __       ____             _             _   _       
> 
>  |  \/  | __ _|  _ \  ___   ___| | _____ _ __| | | |_ __  
> 
>  | |\/| |/ _` | | | |/ _ \ / __| |/ / _ \ '__| | | | '_ \ 
> 
>  | |  | | (_| | |_| | (_) | (__|   <  __/ |  | |_| | |_) |
> 
>  |_|  |_|\__, |____/ \___/ \___|_|\_\___|_|   \___/| .__/ 
> 
>             |_|                                    |_|    
> 
> Starting MqDockerUp V0.16.1 ... 
> 
> 
> 
> 24.04.2023 19:51:02 [info] 	Connected to MQTT broker
> 
> 24.04.2023 19:51:02 [info] 	Checking for new/old containers...
> 
> 24.04.2023 19:51:02 [info] 	Checking for image updates...
> 
> 24.04.2023 19:51:02 [info] 	Image micrib/mqdockerup:latest is up-to-date
> 
> 24.04.2023 19:51:03 [error] 	No Images found:
> 
> 24.04.2023 19:51:03 [error] 	null
> 
> 24.04.2023 19:51:03 [warn] 	Failed to find new digest for image ghcr.io/home-assistant/home-assistant:stable
> 
> 24.04.2023 19:51:03 [error] 	No Images found:
> 
> 24.04.2023 19:51:03 [error] 	null
> 
> 24.04.2023 19:51:03 [warn] 	Failed to find new digest for image ghcr.io/esphome/esphome:latest
> 
> 24.04.2023 19:51:03 [warn] 	Failed to find new digest for image nodered:latest
> 
> 24.04.2023 19:51:03 [info] 	New version available for image zwavejs/zwave-js-ui:latest
> 
> 24.04.2023 19:51:04 [info] 	Image koenkk/zigbee2mqtt:latest is up-to-date
> 
> 24.04.2023 19:51:04 [info] 	New version available for image dpage/pgadmin4:latest
> 
> 24.04.2023 19:51:04 [error] 	No Images found:
> 
> 24.04.2023 19:51:04 [error] 	null
> 
> 24.04.2023 19:51:04 [warn] 	Failed to find new digest for image lscr.io/linuxserver/code-server:latest
> 
> 24.04.2023 19:51:04 [info] 	New version available for image acockburn/appdaemon:latest
> 
> 24.04.2023 19:51:05 [info] 	Image hkotel/mealie:api-v1.0.0beta-5 is up-to-date
> 
> 24.04.2023 19:51:05 [info] 	Image hkotel/mealie:frontend-v1.0.0beta-5 is up-to-date
> 
> 24.04.2023 19:51:05 [error] 	No Images found:
> 
> 24.04.2023 19:51:05 [error] 	null
> 
> 24.04.2023 19:51:05 [warn] 	Failed to find new digest for image lscr.io/linuxserver/cloud9:latest
> 
> 24.04.2023 19:51:05 [info] 	New version available for image portainer/portainer-ce:latest
> 
> 24.04.2023 19:51:06 [warn] 	Failed to find new digest for image rhasspy/rhasspy:latest
> 
> 24.04.2023 19:51:06 [warn] 	Failed to find new digest for image postgres:14.1-alpine
> 
> 24.04.2023 19:51:06 [info] 	New version available for image eclipse-mosquitto:latest
> 
> 24.04.2023 19:51:06 [info] 	Finished checking for image updates
> 
> 24.04.2023 19:51:06 [info] 	Next check in 5 minutes
> 
> 24.04.2023 19:51:06 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
> 
> 24.04.2023 19:51:06 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
> 
> 24.04.2023 19:51:06 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container lscr.io/linuxserver/cloud9:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container eclipse-mosquitto:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container dpage/pgadmin4:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container koenkk/zigbee2mqtt:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container nodered:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container ghcr.io/esphome/esphome:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
> 
> 24.04.2023 19:51:07 [info] 	Removed missing container rhasspy/rhasspy:latest from Home Assistant
> 
> ```

Are you getting anything shown in homeassistant? What exactly is Not working? There are some errors in the logs because it can't find the current version of some images. Currently only dockerhub images are supported.

**Comment by frittes** [comment]
Hi,

most of them are from Docker Hub, but only a few ones are in HA. Because they are removed from mqdockerup.

For example:

mosquitto

```
28.04.2023 17:05:40 [info] 	New version available for image eclipse-mosquitto:latest
28.04.2023 17:05:40 [info] 	Finished checking for image updates
28.04.2023 17:05:40 [info] 	Next check in 5 minutes
```

But the container gets removed.

**Comment by MichelFR** [comment]
@frittes alot of the images where removed because of a missing :latest tag when running container.
In the code i added it so that i new which tag to check for in dockerhub.

Now when it checks if a previously running container is still running it compares it correctly.

In future ill rewrite this, instead of using the container name i should use the container id.
Thanks for bringing this to my attention. Feel free to reopen the issue if it still does not work.
