### ISSUE TITLE
HA MQTT error in logs

### ISSUE THREAD

**Issue by pvh0** [MichelFR/MqDockerUp#388]
Since updateing HA to 2024.11 I get the following error in my logs for every container and update entities show as 'unknown':

`2024-11-11 10:44:48.747 WARNING (MainThread) [homeassistant.components.mqtt.update] Schema violation after processing payload '{"installed_version":"latest: e01bc223b5a6","latest_version":"latest: 4e3611857c4f","release_notes":null,"release_url":null,"entity_picture":null,"title":"esphome/esphome:latest","progress":0,"update":{"state":"available","installed_version":"latest: e01bc223b5a6","latest_version":"latest: 4e3611857c4f","last_check":"2024-11-11T09:44:48.744Z","progress":0,"remaining":0}}' on topic 'mqdockerup/esphome_esphome/update' for entity 'update.esphome_esphome_update': extra keys not allowed @ data['release_notes']`

Anyone else?

**Comment by SiriosDev** [comment]
will be fixed by #385
