### ISSUE TITLE
new versions not showing anymore

### ISSUE THREAD

**Issue by lucize** [MichelFR/MqDockerUp#392]
example:

21.11.2024 22:30:44 [info] 	New version available for image esphome/esphome:latest

but I don't see anything anymore on HA instance

![image](https://github.com/user-attachments/assets/2d65902c-8757-41ff-bb3e-c15abd4d5366)

and if I do a manual update, the update works fine, I'm on the latest release

**Comment by SiriosDev** [comment]
version of HA?
version of Mqdockerup?

**Comment by SiriosDev** [comment]
ok, then it's HA's fault, it changed the way it receives data, in 202.11, it will be fixed in #385

**Comment by lucize** [comment]
didn't expect to be already on the PR :)
