### ISSUE TITLE
Multiple containers with same image

### ISSUE THREAD

**Issue by lodesmets** [MichelFR/MqDockerUp#401]
I have 2 machines with docker. And 2 instances of mqdockerup. But I noticed that if you have multiple containers with the same image (ex 2 instances of adguard. 1 on each machine). 

You can only update 1 with mqdockerup (from homeassistant). The other one you can't update.

I noticed that the update sensor has the name of the image: (ex lscr_io_linuxserver_tautulli_update)
Maybe it should be changed to something more unique?

**Comment by MichelFR** [comment]
Duplicate of: #261
