### ISSUE TITLE
ACCESSTOKENS_GITHUB documentation

### ISSUE THREAD

**Issue by marleyjaffe** [MichelFR/MqDockerUp#409]
Is there documentation on what type and how to generate the appropriate Access Token for `ACCESSTOKENS_GITHUB`?

**Comment by SiriosDev** [comment]
1. Login to github
2. Go [here](https://github.com/settings/tokens)
3. Generate new token (classic)
4. Type a name
5. Select this (should be enough but, to be sure about this, wait for @MichelFR response):
![image](https://github.com/user-attachments/assets/29b4e755-6465-4f5a-8eea-351704d39ade)

**Comment by MichelFR** [comment]
I suggest using a "fine-grained personal access token" not the classic one and the following permissions:

**Repository permissions**
 Read access to merge queues, metadata, code, commit statuses, and pull requests
 
 Probably not all of them are needed but this how i personally am using it.
