### ISSUE TITLE
Failed to find new digest for image

### ISSUE THREAD

**Issue by deluxestyle** [MichelFR/MqDockerUp#42]
I created a docker image for my raspberry
but I get following errors

`
mqdockerup@0.14.9 start
node dist/src/index.js

Starting MqDockerUp V0.14.9 ... 
05.04.2023 09:55:26 [info] 	Connected to MQTT broker
05.04.2023 09:55:26 [info] 	Checking for new/old containers...
05.04.2023 09:55:26 [info] 	Checking for image updates...
05.04.2023 09:55:27 [warn] 	Failed to find new digest for image mqttdockerup:latest
05.04.2023 09:55:27 [error] 	No Images found:
05.04.2023 09:55:27 [error] 	null
05.04.2023 09:55:27 [warn] 	Failed to find new digest for image lscr.io/linuxserver/mariadb:latest
05.04.2023 09:55:28 [error] 	No Images found:
05.04.2023 09:55:28 [error] 	null
05.04.2023 09:55:28 [warn] 	Failed to find new digest for image docker.io/fmartinou/whats-up-docker:latest
05.04.2023 09:55:28 [info] 	Image vaultwarden/server:latest is up-to-date
05.04.2023 09:55:28 [error] 	No Images found:
05.04.2023 09:55:28 [error] 	null
05.04.2023 09:55:28 [warn] 	Failed to find new digest for image docker.io/deconzcommunity/deconz:latest
05.04.2023 09:55:29 [error] 	No Images found:
05.04.2023 09:55:29 [error] 	null
05.04.2023 09:55:29 [warn] 	Failed to find new digest for image docker.io/jc21/nginx-proxy-manager:latest
05.04.2023 09:55:29 [error] 	No Images found:
05.04.2023 09:55:29 [error] 	null
05.04.2023 09:55:29 [warn] 	Failed to find new digest for image eclipse-mosquitto:latest
05.04.2023 09:55:29 [error] 	No Images found:
05.04.2023 09:55:29 [error] 	null
05.04.2023 09:55:29 [warn] 	Failed to find new digest for image docker.io/pihole/pihole:latest
05.04.2023 09:55:30 [error] 	No Images found:
05.04.2023 09:55:30 [error] 	null
05.04.2023 09:55:30 [warn] 	Failed to find new digest for image docker.io/klutchell/dnscrypt-proxy:latest
05.04.2023 09:55:30 [error] 	No Images found:
05.04.2023 09:55:30 [error] 	null
05.04.2023 09:55:30 [warn] 	Failed to find new digest for image ghcr.io/home-assistant/home-assistant:stable
05.04.2023 09:55:30 [info] 	Image portainer/portainer-ce:latest is up-to-date
05.04.2023 09:55:31 [warn] 	Failed to find new digest for image tecnativa/docker-socket-proxy:latest
05.04.2023 09:55:31 [info] 	Finished checking for image updates
05.04.2023 09:55:31 [info] 	Next check in 5 minutes
`

**Comment by MichelFR** [comment]
You seem to have problems connecting to the dockerhub api.

if you call: https://registry.hub.docker.com/v2/repositories/micrib/mqdockerup/tags?name=latest
Do you see any response?

**Comment by deluxestyle** [comment]
yes, I get a response. A json response

**Comment by MichelFR** [comment]
Currently obly dockerhub images are supported. The other ones won't be updatable through mqtt, but should still show properties.
