### ISSUE TITLE
Add hostname to container in Home Assistant

### ISSUE THREAD

**Issue by luisetex84** [MichelFR/MqDockerUp#54]
In case you have the same container in different hosts, the sensor topic in homeassistant is the same. In Home Assistant you have only one entity. You should have at least 2 different entities depending on the number of hosts that run the same container.

I've tried changing the mqtt_topic environment variable to mqdockerup/my_hostname to different values in each host but it not change nothing in homeassistant/sensor/container_name

I think it could be solved by prefixing the hostname on the container_name.

**Comment by MichelFR** [comment]
Thanks for creating an issue and bringing this to my attention.
In future ill implement the possibility to have the same container running on different hosts and distiguish them in MQTT.

Using the hostname as a prefix would probably be the easiest solution as you mentioned.

I'll use this issue to track progress.

**Comment by pepz-de** [comment]
Is here something new at this topic?

**Comment by Wheemer** [comment]
I guess this is my problem with it ignoring multiple contains from the same image source.
