### ISSUE TITLE
Version not detected for some containers, so no indication of new versions

### ISSUE THREAD

**Issue by Gr3ytooth** [MichelFR/MqDockerUp#71]
To start off, great work, I really like the functionality! 

For most of my containers it works really great, but I have some containers where MqDockerUp doesn't detect the current version and for that reason it doesn't detect new versions. Which is a bit annoying and hopefully something that can be fixed.

The containers/images that is not working for me are:

- ghcr.io/blakeblackshear/frigate
- vimagick/glances
- jc21/mariadb-aria
- lscr.io/linuxserver/plex
- lscr.io/linuxserver/radarr
- lscr.io/linuxserver/sabnzbd
- lscr.io/linuxserver/unifi-controller

Is there something I am missing in why these containers doesn't work?

Thanks in advance!

**Comment by MichelFR** [comment]
Currently only images that are hosted on dockerhub are supported. I'm already rewriting the code to make it more dynamic to support more registries.

**Comment by TexiFredrik** [comment]
Okey, I understand.

Keep up the good work! :)

**Comment by MichelFR** [comment]
I rewrote the entire logic of registry handling so that it should be quite easy to add new registries.

For the beginning i added github support.

So mqdockerup supports Dockerhub and ghcr.io images.
