### ISSUE TITLE
Ability to run on multiple docker hosts at the same time

### ISSUE THREAD

**Issue by aheath70** [MichelFR/MqDockerUp#90]
I have 3 Docker hosts, and wanting to feed information into Home Assistant, predominantly so I know when containers are having issues and when there are updates to them

If I install MQDockerUp on multiple hosts, they are overwriting each other, causing MQTT devices in Home Assistant to quickly disappear and then re-appear. I tried using different MQTT topics for each of the servers, but it made no difference.

Would it be possible to make this work with multiple docker hosts simultaneously? Or is there a way that I can change an option to get it to work currently?

**Comment by MichelFR** [comment]
> I have 3 Docker hosts, and wanting to feed information into Home Assistant, predominantly so I know when containers are having issues and when there are updates to them
> 
> 
> 
> If I install MQDockerUp on multiple hosts, they are overwriting each other, causing MQTT devices in Home Assistant to quickly disappear and then re-appear. I tried using different MQTT topics for each of the servers, but it made no difference.
> 
> 
> 
> Would it be possible to make this work with multiple docker hosts simultaneously? Or is there a way that I can change an option to get it to work currently?

Currently it's not supported or even possible. I'll come back to you as soon as I implemented the functionality to support multiple hosts.
