### ISSUE TITLE
"No registry for the image" crashes container

### ISSUE THREAD

**Issue by coharness** [MichelFR/MqDockerUp#98]
I am using the service as a Docker container and it crashes every single time when trying to check for updates, specifically on Plex. I couldn't pull the actual text but was able to get a screenshot of it
![image](https://github.com/MichelFR/MqDockerUp/assets/7691875/6a3a2d11-93cb-4a9c-b9ec-8709eb039ef3)
I stopped the Plex container and it did get through more, but then crashed on another container later on.

**Comment by MichelFR** [comment]
Thanks for you report, currently lscr.io is not supported.
But its already implemented and will work in the next version.

But it should not be crashing. Ill look into that thanks.
